# Generated by Django 5.2.17 on 2026-10-04 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(blank=True, max_length=20, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Département",
                "verbose_name_plural": "Départements",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Employe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "matricule",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Matricule"
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=150, verbose_name="Prénom")),
                (
                    "date_naissance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "lieu_naissance",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Lieu de naissance"
                    ),
                ),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        max_length=10,
                        verbose_name="Sexe",
                    ),
                ),
                (
                    "situation_matrimoniale",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Situation matrimoniale"
                    ),
                ),
                (
                    "nationalite",
                    models.CharField(
                        default="Guinéenne", max_length=50, verbose_name="Nationalité"
                    ),
                ),
                ("adresse", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "numero_cni",
                    models.CharField(blank=True, max_length=50, verbose_name="N° CNI"),
                ),
                (
                    "numero_cnss",
                    models.CharField(blank=True, max_length=50, verbose_name="N° CNSS"),
                ),
                ("date_embauche", models.DateField(verbose_name="Date d'embauche")),
                (
                    "type_contrat",
                    models.CharField(
                        choices=[
                            ("CDI", "CDI"),
                            ("CDD", "CDD"),
                            ("STAGE", "Stage"),
                            ("TEMPORAIRE", "Temporaire"),
                        ],
                        max_length=30,
                        verbose_name="Type de contrat",
                    ),
                ),
                (
                    "salaire_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Salaire de base (GNF)",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("suspendu", "Suspendu"),
                            ("parti", "Parti"),
                        ],
                        default="actif",
                        max_length=30,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="employes/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Supprimé par",
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employes",
                        to="rh.departement",
                        verbose_name="Département",
                    ),
                ),
                (
                    "superieur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordonnes",
                        to="rh.employe",
                        verbose_name="Supérieur hiérarchique",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employe_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compte utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employé",
                "verbose_name_plural": "Employés",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.AddField(
            model_name="departement",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departements_diriges",
                to="rh.employe",
                verbose_name="Responsable",
            ),
        ),
        migrations.CreateModel(
            name="Contrat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "numero",
                    models.CharField(max_length=50, unique=True, verbose_name="Numéro"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CDI", "CDI"),
                            ("CDD", "CDD"),
                            ("STAGE", "Stage"),
                            ("TEMPORAIRE", "Temporaire"),
                        ],
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                (
                    "date_fin",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "salaire",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Salaire contractuel",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contrats/",
                        verbose_name="Document scanné",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("expire", "Expiré"),
                            ("rompu", "Rompu"),
                        ],
                        default="actif",
                        max_length=30,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "renouvellement",
                    models.BooleanField(default=False, verbose_name="Renouvelable"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrats",
                        to="rh.employe",
                        verbose_name="Employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrat",
                "verbose_name_plural": "Contrats",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Conge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "numero",
                    models.CharField(max_length=50, unique=True, verbose_name="Numéro"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("annuel", "Congé annuel"),
                            ("maladie", "Congé maladie"),
                            ("maternite", "Congé maternité"),
                            ("exceptionnel", "Congé exceptionnel"),
                        ],
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                ("date_fin", models.DateField(verbose_name="Date de fin")),
                ("nombre_jours", models.IntegerField(verbose_name="Nombre de jours")),
                ("motif", models.TextField(blank=True, verbose_name="Motif")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("valide", "Validé"),
                            ("refuse", "Refusé"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=30,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de validation"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conges_valides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conges",
                        to="rh.employe",
                        verbose_name="Employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Congé",
                "verbose_name_plural": "Congés",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                ("date_fin", models.DateField(verbose_name="Date de fin")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("maladie", "Maladie"),
                            ("injustifiee", "Non justifiée"),
                            ("autorisee", "Autorisée"),
                        ],
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                ("motif", models.TextField(blank=True, verbose_name="Motif")),
                (
                    "justificatif",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="absences/%Y/%m/",
                        verbose_name="Justificatif",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("valide", "Validé"),
                            ("refuse", "Refusé"),
                        ],
                        default="en_attente",
                        max_length=30,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="rh.employe",
                        verbose_name="Employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Absence",
                "verbose_name_plural": "Absences",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                ("date_evaluation", models.DateField(verbose_name="Date d'évaluation")),
                ("periode", models.CharField(max_length=30, verbose_name="Période")),
                (
                    "note_globale",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Note globale (/20)",
                    ),
                ),
                (
                    "points_forts",
                    models.TextField(blank=True, verbose_name="Points forts"),
                ),
                (
                    "points_ameliorer",
                    models.TextField(blank=True, verbose_name="Points à améliorer"),
                ),
                ("objectifs", models.TextField(blank=True, verbose_name="Objectifs")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="rh.employe",
                        verbose_name="Employé évalué",
                    ),
                ),
                (
                    "evaluateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations_faites",
                        to="rh.employe",
                        verbose_name="Évaluateur",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation",
                "verbose_name_plural": "Évaluations",
                "ordering": ["-date_evaluation"],
            },
        ),
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "formateur",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Formateur"
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                ("date_fin", models.DateField(verbose_name="Date de fin")),
                (
                    "lieu",
                    models.CharField(blank=True, max_length=200, verbose_name="Lieu"),
                ),
                (
                    "cout",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Coût (GNF)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="formations",
                        to="rh.employe",
                        verbose_name="Participants",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formation",
                "verbose_name_plural": "Formations",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Poste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Intitulé")),
                (
                    "salaire_min",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Salaire minimum",
                    ),
                ),
                (
                    "salaire_max",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Salaire maximum",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postes",
                        to="rh.departement",
                        verbose_name="Département",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poste",
                "verbose_name_plural": "Postes",
                "ordering": ["nom"],
            },
        ),
        migrations.AddField(
            model_name="employe",
            name="poste",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employes",
                to="rh.poste",
                verbose_name="Poste",
            ),
        ),
        migrations.CreateModel(
            name="Presence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "heure_arrivee",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure d'arrivée"
                    ),
                ),
                (
                    "heure_depart",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de départ"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("present", "Présent"),
                            ("absent", "Absent"),
                            ("retard", "Retard"),
                            ("mission", "Mission"),
                            ("conge", "Congé"),
                            ("repos", "Repos"),
                            ("depart_anticipe", "Départ anticipé"),
                        ],
                        default="present",
                        max_length=30,
                        verbose_name="Statut",
                    ),
                ),
                ("motif", models.TextField(blank=True, verbose_name="Motif")),
                (
                    "justificatif",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="justificatifs/%Y/%m/",
                        verbose_name="Justificatif",
                    ),
                ),
                (
                    "heures_travaillees",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Heures travaillées",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presences",
                        to="rh.employe",
                        verbose_name="Employé",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Présence",
                "verbose_name_plural": "Présences",
                "ordering": ["-date", "employe__nom"],
            },
        ),
        migrations.CreateModel(
            name="SoldeConge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                ("annee", models.IntegerField(verbose_name="Année")),
                (
                    "solde_initial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Solde initial",
                    ),
                ),
                (
                    "jours_acquis",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Jours acquis",
                    ),
                ),
                (
                    "jours_pris",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Jours pris",
                    ),
                ),
                (
                    "solde_restant",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Solde restant",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soldes_conges",
                        to="rh.employe",
                        verbose_name="Employé",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solde de congés",
                "verbose_name_plural": "Soldes de congés",
            },
        ),
        migrations.CreateModel(
            name="JoursTravailles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                ("mois", models.IntegerField(verbose_name="Mois")),
                ("annee", models.IntegerField(verbose_name="Année")),
                (
                    "jours_theoriques",
                    models.IntegerField(default=0, verbose_name="Jours théoriques"),
                ),
                (
                    "jours_presents",
                    models.IntegerField(default=0, verbose_name="Jours présents"),
                ),
                (
                    "absences_non_justifiees",
                    models.IntegerField(
                        default=0, verbose_name="Absences non justifiées"
                    ),
                ),
                (
                    "jours_travailles",
                    models.IntegerField(default=0, verbose_name="Jours travaillés"),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jours_travailles",
                        to="rh.employe",
                        verbose_name="Employé",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jours travaillés",
                "verbose_name_plural": "Jours travaillés",
                "unique_together": {("employe", "mois", "annee")},
            },
        ),
        migrations.AddIndex(
            model_name="employe",
            index=models.Index(
                fields=["matricule"], name="rh_employe_matricu_966fc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employe",
            index=models.Index(fields=["statut"], name="rh_employe_statut_6eea2c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="presence",
            unique_together={("employe", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="soldeconge",
            unique_together={("employe", "annee")},
        ),
    ]
