# Generated by Django 5.2.17 on 2026-10-09 13:39

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rh", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Code client"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("particulier", "Particulier"),
                            ("entreprise", "Entreprise"),
                            ("administration", "Administration"),
                            ("ong", "ONG"),
                            ("collectivite", "Collectivité"),
                            ("commerce", "Commerce"),
                            ("hotel", "Hôtel"),
                            ("ecole", "Établissement scolaire"),
                            ("autre", "Autre"),
                        ],
                        default="particulier",
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("suspendu", "Suspendu"),
                            ("archive", "Archivé"),
                        ],
                        default="actif",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=200, verbose_name="Nom / Raison sociale"
                    ),
                ),
                (
                    "prenom",
                    models.CharField(blank=True, max_length=150, verbose_name="Prénom"),
                ),
                (
                    "sigle",
                    models.CharField(blank=True, max_length=50, verbose_name="Sigle"),
                ),
                (
                    "sexe",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        max_length=10,
                        verbose_name="Sexe",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(max_length=30, verbose_name="Téléphone"),
                ),
                (
                    "telephone2",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone 2"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("adresse", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "ville",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "quartier",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Quartier"
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Zone de collecte"
                    ),
                ),
                (
                    "num_contribuable",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="N° Contribuable"
                    ),
                ),
                (
                    "num_rccm",
                    models.CharField(blank=True, max_length=50, verbose_name="N° RCCM"),
                ),
                (
                    "contact_nom",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nom du contact"
                    ),
                ),
                (
                    "contact_fonction",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Fonction du contact"
                    ),
                ),
                (
                    "contact_telephone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone contact"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="clients/",
                        verbose_name="Photo / Logo",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
                (
                    "compte_utilisateur",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compte portail client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Supprimé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="ContratClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "numero",
                    models.CharField(max_length=50, unique=True, verbose_name="Numéro"),
                ),
                (
                    "prestation",
                    models.CharField(max_length=200, verbose_name="Prestation"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "frequence",
                    models.CharField(
                        choices=[
                            ("quotidien", "Quotidien"),
                            ("hebdomadaire", "Hebdomadaire"),
                            ("bimensuel", "Bimensuel"),
                            ("mensuel", "Mensuel"),
                            ("trimestriel", "Trimestriel"),
                            ("annuel", "Annuel"),
                            ("ponctuel", "Ponctuel"),
                        ],
                        default="mensuel",
                        max_length=30,
                        verbose_name="Fréquence",
                    ),
                ),
                (
                    "zone",
                    models.CharField(blank=True, max_length=100, verbose_name="Zone"),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                (
                    "date_fin",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "reconduction_tacite",
                    models.BooleanField(
                        default=False, verbose_name="Reconduction tacite"
                    ),
                ),
                (
                    "jours_preavis",
                    models.IntegerField(default=30, verbose_name="Jours de préavis"),
                ),
                (
                    "tarif",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Tarif (GNF)"
                    ),
                ),
                (
                    "tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="TVA (%)",
                    ),
                ),
                (
                    "modalite_paiement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("virement", "Virement bancaire"),
                            ("cheque", "Chèque"),
                            ("mobile_money", "Mobile Money"),
                            ("prelevement", "Prélèvement"),
                        ],
                        default="especes",
                        max_length=30,
                        verbose_name="Modalité",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("actif", "Actif"),
                            ("suspendu", "Suspendu"),
                            ("expire", "Expiré"),
                            ("resilie", "Résilié"),
                            ("archive", "Archivé"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date validation"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contrats_clients/",
                        verbose_name="Contrat signé",
                    ),
                ),
                (
                    "conditions_particulieres",
                    models.TextField(
                        blank=True, verbose_name="Conditions particulières"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrats",
                        to="clients.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contrats_affectes",
                        to="rh.employe",
                        verbose_name="Équipe / Superviseur",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contrats_clients_valides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrat client",
                "verbose_name_plural": "Contrats clients",
                "ordering": ["-date_debut"],
            },
            bases=(models.Model, core.models.NumeroAutoMixin),
        ),
        migrations.CreateModel(
            name="Prestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Code"),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "tarif_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Tarif de base (GNF)",
                    ),
                ),
                (
                    "unite",
                    models.CharField(blank=True, max_length=50, verbose_name="Unité"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestation",
                "verbose_name_plural": "Prestations",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Relance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "facture_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence facture"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("appel", "Appel téléphonique"),
                            ("courrier", "Courrier"),
                            ("visite", "Visite sur site"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "date_relance",
                    models.DateField(auto_now_add=True, verbose_name="Date"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                (
                    "montant_reclame",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Montant réclamé",
                    ),
                ),
                (
                    "reponse_client",
                    models.TextField(blank=True, verbose_name="Réponse client"),
                ),
                (
                    "prochaine_relance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prochaine relance"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relances",
                        to="clients.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relance",
                "verbose_name_plural": "Relances",
                "ordering": ["-date_relance"],
            },
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["code"], name="clients_cli_code_d90b4a_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["type", "statut"], name="clients_cli_type_ca0890_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["zone"], name="clients_cli_zone_16b450_idx"),
        ),
        migrations.AddIndex(
            model_name="contratclient",
            index=models.Index(fields=["numero"], name="clients_con_numero_f192f9_idx"),
        ),
        migrations.AddIndex(
            model_name="contratclient",
            index=models.Index(
                fields=["client", "statut"], name="clients_con_client__4c73d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contratclient",
            index=models.Index(
                fields=["date_fin"], name="clients_con_date_fi_32bbc6_idx"
            ),
        ),
    ]
