# Generated by Django 5.2.17 on 2026-10-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Etablissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("sigle", models.CharField(blank=True, max_length=20)),
                ("adresse", models.TextField()),
                (
                    "telephone1",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Téléphone principal",
                    ),
                ),
                (
                    "telephone2",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Téléphone secondaire",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("site_web", models.URLField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="etablissement/"
                    ),
                ),
                ("devise", models.CharField(default="F CFA", max_length=10)),
                (
                    "systeme_notation",
                    models.CharField(
                        choices=[
                            ("sur20", "Sur 20"),
                            ("sur100", "Sur 100"),
                            ("lettre", "Lettres"),
                        ],
                        default="sur20",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Établissement",
                "verbose_name_plural": "Établissements",
            },
        ),
    ]
