# Generated by Django 5.2.17 on 2026-10-04 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "login_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Connexion"),
                ),
                (
                    "logout_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Déconnexion"
                    ),
                ),
                ("success", models.BooleanField(default=True, verbose_name="Succès")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de connexion",
                "verbose_name_plural": "Historique des connexions",
                "ordering": ["-login_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=50, verbose_name="Module")),
                (
                    "action",
                    models.CharField(
                        help_text="create, update, delete, validate, cancel...",
                        max_length=50,
                        verbose_name="Action",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, verbose_name="Modèle")),
                (
                    "object_id",
                    models.IntegerField(blank=True, null=True, verbose_name="ID objet"),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Anciennes valeurs"
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Nouvelles valeurs"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'audit",
                "verbose_name_plural": "Journal d'audit",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="config_audi_user_id_2e4b92_idx",
                    ),
                    models.Index(
                        fields=["module", "model_name"],
                        name="config_audi_module_1b85b4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="Nom du fichier"),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="documents/%Y/%m/", verbose_name="Fichier"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("contrat", "Contrat"),
                            ("facture", "Facture"),
                            ("recu", "Reçu"),
                            ("bon_commande", "Bon de commande"),
                            ("bon_livraison", "Bon de livraison"),
                            ("justificatif", "Justificatif"),
                            ("contrat_travail", "Contrat de travail"),
                            ("piece_admin", "Pièce administrative"),
                            ("document_vehicule", "Document véhicule"),
                            ("document_fournisseur", "Document fournisseur"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        help_text="Ex: rh, paie, tresorerie, stocks...",
                        max_length=50,
                        verbose_name="Module",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID objet lié"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["module", "object_id"],
                        name="config_docu_module_1ca5a2_idx",
                    ),
                    models.Index(fields=["type"], name="config_docu_type_95d7b6_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("alerte", "Alerte"),
                            ("validation", "Validation"),
                            ("systeme", "Système"),
                        ],
                        default="info",
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True,
                        help_text="Ex: rh, paie, tresorerie, stocks...",
                        max_length=50,
                        verbose_name="Module source",
                    ),
                ),
                (
                    "lien",
                    models.CharField(
                        blank=True,
                        help_text="URL vers lequel rediriger l'utilisateur",
                        max_length=300,
                        verbose_name="Lien d'action",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lu le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="config_noti_user_id_840a3f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Numerotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "type_document",
                    models.CharField(
                        help_text="Ex: FACT, BC, DEP, ENC, DEC, RH-EMP, TR, VEH",
                        max_length=50,
                        verbose_name="Type de document",
                    ),
                ),
                ("prefixe", models.CharField(max_length=20, verbose_name="Préfixe")),
                ("annee", models.IntegerField(verbose_name="Année")),
                (
                    "dernier_numero",
                    models.IntegerField(default=0, verbose_name="Dernier numéro"),
                ),
                (
                    "format",
                    models.CharField(
                        default="{prefix}-{year}-{num:06d}",
                        help_text="Variables : {prefix}, {year}, {num}",
                        max_length=100,
                        verbose_name="Format",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Numérotation",
                "verbose_name_plural": "Numérotations",
                "ordering": ["-annee", "type_document"],
                "unique_together": {("type_document", "annee")},
            },
        ),
    ]
